import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const code=readFileSync(new URL('../../cloudflare-api.js',import.meta.url),'utf8');
function context(search){const requests=[];const fetch=async(url,init={})=>{requests.push({url:String(url),init});if(String(url).startsWith('data:'))return new Response(new Blob(['photo'],{type:'image/jpeg'}));return Response.json(String(url).includes('/upload')?{id:'uploaded'}:{ok:true});};const window={fetch,HousesBackendConfig:{backend:'appwrite',cloudflareUrl:'https://test.workers.dev'}};vm.runInNewContext(code,{window,location:{search,href:'https://projetosetags.github.io/'},URL,URLSearchParams,Response,Blob,FormData});return{window,requests};}
test('Production retains Appwrite until explicit activation',()=>{const c=context('');assert.equal(c.window.__HOUSES_BACKEND,undefined);});
test('Cloudflare sends pastoral credentials in headers and photos as binary',async()=>{const c=context('?backend=cloudflare');await c.window.HousesAppwrite.pastoralPost('?token=private',{action:'create_communication'});assert.equal(c.requests[0].url,'https://test.workers.dev/pastoral-api');assert.equal(c.requests[0].init.headers['X-Admin-Token'],'private');await c.window.fetch('https://legacy.supabase.co/functions/v1/houses-api?id=0001',{method:'POST',body:JSON.stringify({meeting_date:'2026-10-10',photo_data_url:'data:image/jpeg;base64,eA=='})});const upload=c.requests.find(r=>r.url.includes('/upload'));assert.ok(upload.init.body instanceof Blob);const sent=JSON.parse(c.requests.at(-1).init.body);assert.equal(sent.photo_file_id,'uploaded');assert.equal(sent.photo_data_url,undefined);});
test('Material replacement uses a binary upload and links the existing record',async()=>{const c=context('?backend=cloudflare'),fd=new FormData();fd.append('file',new Blob(['pdf'],{type:'application/pdf'}),'guide.pdf');fd.append('material_id','existing');await c.window.fetch('https://legacy.supabase.co/functions/v1/material-upload?token=private',{method:'POST',body:fd});assert.ok(c.requests[0].init.body instanceof Blob);const sent=JSON.parse(c.requests[1].init.body);assert.equal(sent.action,'link_material');assert.equal(sent.id,'existing');assert.equal(sent.upload_file_id,'uploaded');});
